# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)
development:
  adapter: mysql
  encoding: utf8
  database: chat_sandbox
  username: root
  password:
  host: localhost